apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: oracle-cloud-provider
  name: oracle-cloud-provider
spec:
  selector:
    matchLabels:
      name: oracle-cloud-provider
  template:
    metadata:
      labels:
        name: oracle-cloud-provider
    spec:
      containers:
        - name: oracle-cloud-fuse
          image:  uk-london-1.ocir.io/lrtfqsmony6u/s3fs:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: oracle-cloud-credentials
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: oracle-cloud-fs
              mountPath: /var/s3
              mountPropagation: "Bidirectional" # this was the key to make it work.
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: oracle-cloud-fs
          hostPath:
            path: /tmp/s3


