apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: indexing-step-
  namespace: argo
spec:
  entrypoint: ingestion
  templates:
  - container:
      command:
      - python
      - ingestion/main.py
      env:
      - name: POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            key: POSTGRES_HOST
            name: postgres-database-secrets
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: postgres-database-secrets
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            key: POSTGRES_USER
            name: postgres-database-secrets
      - name: POSTGRES_PORT
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PORT
            name: postgres-database-secrets
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            key: POSTGRES_DB
            name: postgres-database-secrets
      image: espymur/rag-doc-ingestion:latest
    name: ingestion-44fd88
  - name: ingestion
    steps:
    - - name: ingestion
        template: ingestion-44fd88
