FROM python:3.10 as python-deps
LABEL maintainer="Espoir Murhabazi<espoir.mur [] gmail>"

ARG PIP_SECTION
# Never prompt the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 
ENV PYROOT /opt/venv
ENV PYTHONUSERBASE $PYROOT

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        curl \
        build-essential\
        software-properties-common \
        libpq5
COPY Pipfile Pipfile.lock ./
RUN python -m venv $PYROOT
ENV PATH=$PYROOT/bin:$PATH
# Install inside the virtualenv  
RUN python -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --categories=${PIP_SECTION} --system --deploy
RUN pip install torch==2.2.0 --index-url https://download.pytorch.org/whl/cpu


FROM python:3.10-slim AS runtime

ARG COMPONENT_NAME
ARG COMPONENT_PATH
ENV PYROOT /opt/venv
ENV PYTHONUSERBASE $PYROOT

# copy only the content of virtualenv
COPY --from=python-deps $PYROOT/lib $PYROOT/lib
# should I have copied this?
COPY --from=python-deps $PYROOT/bin $PYROOT/bin


RUN useradd --create-home es.py
RUN mkdir /home/${COMPONENT_NAME}
ENV WORKING_DIR=/home/${COMPONENT_NAME}
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
ENV PATH="$PYROOT/bin:$PATH"
ENV PYTHONPATH="${PYTHONPATH}:${WORKING_DIR}"
COPY ${COMPONENT_PATH} ${WORKING_DIR}/src/${COMPONENT_NAME}
COPY src/shared ${WORKING_DIR}/src/shared
WORKDIR ${WORKING_DIR}
RUN chown -R es.py:es.py ${WORKING_DIR}
RUN chmod -R 755 ${WORKING_DIR}
USER es.py
