FROM python:3.10 as base
LABEL maintainer="Espoir Murhabazi<espoir.mur [] gmail>"

ARG PIP_SECTION
# Never prompt the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 



FROM base AS python-deps
ENV PYROOT /pyroot
ENV PYTHONUSERBASE $PYROOT

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        curl \
        build-essential\
        software-properties-common \
        libpq5
COPY Pipfile Pipfile.lock ./
RUN python -m pip install --upgrade pip
RUN pip install pipenv
RUN PIP_USER=1 pipenv install --categories=${PIP_SECTION} --system --deploy

FROM python:3.10-slim AS runtime

ARG COMPONENT_NAME
ARG COMPONENT_PATH
ENV PYROOT /pyroot
ENV PYTHONUSERBASE $PYROOT

COPY --from=python-deps $PYROOT/lib $PYROOT/lib
COPY --from=python-deps $PYROOT/bin $PYROOT/bin
COPY --from=python-deps /usr/local/lib/python3.10/site-packages/certifi $PYROOT/lib/python3.10/site-packages/certifi
COPY --from=python-deps /usr/local/lib/python3.10/site-packages/filelock $PYROOT/lib/python3.10/site-packages/filelock
COPY --from=python-deps /usr/local/lib/python3.10/site-packages/packaging $PYROOT/lib/python3.10/site-packages/packaging
COPY --from=python-deps /usr/local/lib/python3.10/site-packages/packaging-24.1.dist-info $PYROOT/lib/python3.10/site-packages/packaging-24.1.dist-info
COPY --from=python-deps /usr/local/lib/python3.10/site-packages/filelock-3.16.1.dist-info $PYROOT/lib/python3.10/site-packages/filelock-3.16.1.dist-info


RUN useradd --create-home es.py
RUN mkdir /home/${COMPONENT_NAME}
ENV WORKING_DIR=/home/${COMPONENT_NAME}
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
ENV PATH="$PYROOT/bin:$PATH"
ENV PYTHONPATH="${PYTHONPATH}:${WORKING_DIR}"
COPY ${COMPONENT_PATH} ${WORKING_DIR}/src/${COMPONENT_NAME}
COPY src/shared ${WORKING_DIR}/src/shared
WORKDIR ${WORKING_DIR}
RUN chown -R es.py:es.py ${WORKING_DIR}
RUN chmod -R 755 ${WORKING_DIR}
USER es.py
