apiVersion: v1
kind: Secret
metadata:
  name: oracle-cloud-credentials
type: Opaque
data:
  ORACLE_CLOUD_SECRET: "NUpYaFpjSW0vOTBFRGpNT0hnVjdxSVpwNUtoQkZFYkRiWGRmeUhLbHhrMD0="
  OCI_BUCKET: "YmlvLWdwdC1lbWJlZGRpbmc="
  REGION : "dWstbG9uZG9uLTE="
  TENANT_ID: "bHJ0ZnFzbW9ueTZ1"
  ACCESS_KEY_ID: "OTkzMjcyOTE2M2JlYmMwNzE3Mzk1YzUxNDNiYjEwOWY2YjhkMTZiYw=="



